baseURL         = "http://pktito.github.io"
contentdir      = "content"
layoutdir       = "layouts"
publishdir      = "public"
languageCode    = "es-ES"
title           = "Roberto Zazo"
theme           = "hugo-goa"

[params]
    locale      = "es-ES"

[Author]
    author      = "Roberto Zazo"
    email       = "roberto.zazo@gmail.com"
    facebook    = "username"
    googleplus  = "+username"
    gitlab      = "rzazo"
    github      = "pktito"
    twitter     = "username"
    reddit      = "username"
    linkedin    = "username"
    xing        = "username"
    stackoverflow   = "users/XXXXXXX/username"
    snapchat    = "username"
    instagram   = "rzazo"
    youtube     = "user/username" # or channel/channelname
    soundcloud  = "username"

[[menu.main]]
    Name        = "Roberto Zazo"
    URL         = ""
    weight      = 1

[[menu.main]]
    name        = "about"
    identifier  = "about"
    weight      = 200
    url         = "/about/"

[[menu.main]]
    name        = "Tags"
    url         = "tags"
    weight      = 3
